# Generated by Django 5.2.7 on 2025-11-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Axolotl', '0002_usuario_profile_image_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='genero',
            field=models.CharField(choices=[('pop', 'Pop'), ('rock', 'Rock'), ('hip-hop', 'Hip-Hop'), ('electrónica', 'Electrónica'), ('indie', 'Indie'), ('jazz', 'Jazz'), ('clásica', 'Clásica'), ('reggaeton', 'Reggaeton'), ('k-pop', 'K-Pop'), ('latino', 'Latino')], max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('vinilo', 'Vinilo'), ('cd', 'CD'), ('casete', 'Casete')], max_length=50),
        ),
    ]
